const mongoose = require("mongoose");

const { Schema, model } = mongoose;

const JobApplicationSchema = new Schema({
    firstName: { type: String },
    lastName: { type: String },
    middleName: { type: String },
    dateOfBirth: { type: String },
    streetAddress: { type: String },
    city: { type: String },
    country: { type: String },
    postCode: { type: String },
    email: { type: String },
    phoneNumber: { type: String },
    applyPosition: { type: String },
    startDate: { type: String },
    insuranceNumber: { type: String },
    ukCitizen: { type: String },
    workAuthority: { type: String },
    workPermit: { type: String },
    contactAddress: { type: String },
    driverLicense: { type: Boolean },
    companyOne: { type: String },
    supervisorOne: { type: String },
    companyPhoneOne: { type: String },
    companyEmailOne: { type: String },
    companyAddressOne: { type: String },
    companyTitleOne: { type: String },
    companyCityOne: { type: String },
    companyCountryOne: { type: String },
    companyPostCodeOne: { type: String },
    responsibilityOne: { type: String },
    reasonForLeavingOne: { type: String },
    companyTwo: { type: String },
    supervisorTwo: { type: String },
    companyPhoneTwo: { type: String },
    companyEmailTwo: { type: String },
    companyAddressTwo: { type: String },
    companyTitleTwo: { type: String },
    companyCityTwo: { type: String },
    companyCountryTwo: { type: String },
    companyPostCodeTwo: { type: String },
    responsibilityTwo: { type: String },
    reasonForLeavingTwo: { type: String },
    collegeName: { type: String },
    collegeStartDate: { type: String },
    collegeFinishDate: { type: String },
    collegeAddress: { type: String },
    collegeCity: { type: String },
    collegeCountry: { type: String },
    collegePostCode: { type: String },
    collegeGrades: { type: String },
    universityName: { type: String },
    universityStartDate: { type: String },
    universityFinishDate: { type: String },
    universityAddress: { type: String },
    universityCity: { type: String },
    universityCountry: { type: String },
    universityPostCode: { type: String },
    universityGrades: { type: String },
    otherSchoolName: { type: String },
    otherSchoolStartDate: { type: String },
    otherSchoolFinishDate: { type: String },
    otherSchoolAddress: { type: String },
    otherSchoolCity: { type: String },
    otherSchoolCountry: { type: String },
    otherSchoolPostCode: { type: String },
    otherSchoolGrades: { type: String },
    refereeOneName: { type: String },
    refereeOneRelationship: { type: String },
    refereeOnePhone: { type: String },
    refereeOneCompany: { type: String },
    refereeOneEmail: { type: String },
    refereeOneAddress: { type: String },
    refereeTwoName: { type: String },
    refereeTwoRelationship: { type: String },
    refereeTwoPhone: { type: String },
    refereeTwoCompany: { type: String },
    refereeTwoEmail: { type: String },
    refereeTwoAddress: { type: String },
    criminalRecord: { type: String },
    investigation: { type: String },
    disqualified: { type: String },
    furtherDetails: { type: String },
    agreement: { type: Boolean },
},
    {
        timestamps: true,
    }
);

const JobApplicationModel = model("JobApplication", JobApplicationSchema);

module.exports = JobApplicationModel;
